apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-service-canary.fullname" . }}-canary
  labels:
    {{- include "user-service-canary.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "user-service-canary.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-service-canary.fullname" . }}-stable
  labels:
    {{- include "user-service-canary.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "user-service-canary.selectorLabels" . | nindent 4 }}
